### ISSUE TITLE
Dashboard hanging & crashing Simhub

### ISSUE THREAD

**Issue by Nammurg** [Romainrob/SimHub-iRacing_Pack#1]
Dashboard Hanging, SimHub is unresponsive and freezes the whole machine.

It seems that the below error is repeated over and over and over again in the SimHub log files...

[2020-12-10 21:09:51,311] WARN - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Romainrob.theManyFacedDash.TheManyFacedDash.<DataUpdate>g__DashTexture|15_0(<>c__DisplayClass15_0& )
   at Romainrob.theManyFacedDash.TheManyFacedDash.DataUpdate(PluginManager pluginManager, GameData& data)
   at SimHub.Plugins.PluginManager.manager_DataUpdated(GameData data, IGameManager manager)

[2020-12-10 21:09:51,327] WARN - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Romainrob.theManyFacedDash.TheManyFacedDash.<DataUpdate>g__DashTexture|15_0(<>c__DisplayClass15_0& )
   at Romainrob.theManyFacedDash.TheManyFacedDash.DataUpdate(PluginManager pluginManager, GameData& data)
   at SimHub.Plugins.PluginManager.manager_DataUpdated(GameData data, IGameManager manager)

**Comment by Romainrob** [comment]
Hi.
It seems something went wrong with the the many-faced dash settings.
I've had one similar report before but couldn't replicate the issue.

Could you please share this file : C:\Program Files (x86)\SimHub\PluginsData\Common\TheManyFacedDash.GeneralSettings.json

Then :
1. Close SimHub
2. Delete the TheManyFacedDash.GeneralSettings.json file
3. Restart SimHub
4. Apply your settings in the UI
5. And restart SimHub to save them to the file files again.

**Comment by Nammurg** [comment]
Hi, 
File attached as requested.
Performed the fix, this seems to have fixed the issue!

[TheManyFacedDash.GeneralSettings.zip](https://github.com/Romainrob/SimHub-iRacing_Pack/files/5682936/TheManyFacedDash.GeneralSettings.zip)

**Comment by Romainrob** [comment]
Hi,
Thanks for the file.
I didn't find anything wrong with it though. It loaded just fine for me.
And I can't break the settings no matter how much I mess with the UI.
I admit I'm a bit confused as to what's causing this bug exactly.
Still I'll implement some changes for the next update. Hopefully they will prevent this.
Thanks for reporting the issue.
